// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD0RSL8MQYeVQwpvL2ADHfHKbTMBbmo8w',
    appId: '1:388043547131:web:ae11ef8c959af125d92b5e',
    messagingSenderId: '388043547131',
    projectId: 'w4-natiee',
    authDomain: 'w4-natiee.firebaseapp.com',
    storageBucket: 'w4-natiee.firebasestorage.app',
    measurementId: 'G-0XV8VGEC04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8c3-whT49uGF5x5kUnEiEnpJ3O9qldEE',
    appId: '1:388043547131:android:7ac81555e03a5899d92b5e',
    messagingSenderId: '388043547131',
    projectId: 'w4-natiee',
    storageBucket: 'w4-natiee.firebasestorage.app',
  );
}
